version: '3'
services:
  web:
    build: .
    ports:
      - "${WebPort}:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  dockbook:
    image: "lesmatheson0/main:dockbook"
    command: ["bash","-l"]
    volumes:
      - .:/data
    depends_on: ["web","redis"]
    stdin_open: true
    tty: true
  gobuild:
    build: ../go-test
    volumes: [".:/app"]
    depends_on: ["web","redis"]
    stdin_open: true
    tty: true
